#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$PATH:~/bin:~/.composer/vendor/bin

alias c='clear'
alias ls='ls -AFGhlp'
alias brrr="yes > /dev/null & yes > /dev/null & yes > /dev/null & yes > /dev/null &"
alias ahhh="killall yes"
alias crush="pngcrush -rem allb -brute -reduce"
alias del="trash"

alias vm="ssh vagrant@127.0.0.1 -p 2222"
