#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=~/bin:~/.composer/vendor/bin:/usr/local/bin:$PATH

alias c='clear'
alias ls='ls -AFGhlp'
alias mkdir='mkdir -p'
alias brrr="yes > /dev/null & yes > /dev/null & yes > /dev/null & yes > /dev/null &"
alias ahhh="killall yes"
alias crush="pngcrush -rem allb -brute -reduce"
alias del="trash"
alias homestead='function __homestead() { (cd ~/Homestead && vagrant $*); unset -f __homestead; }; __homestead'
